scrape_configs:
  - job_name: 'boring-name-service'
    scrape_interval: 15s

    static_configs:
      - targets: ['app.local:8100']

  - job_name: 'cute-name-service'
    scrape_interval: 15s

    static_configs:
      - targets: ['app.local:8200']

  - job_name: 'greeting-service'
    scrape_interval: 15s

    static_configs:
      - targets: ['app.local:8080']
